<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Common.targets" />

  <PropertyGroup>
    <Use_DalamudPackager>false</Use_DalamudPackager>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)\BossMod\BossMod.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>

    <ProjectReference Include="$(MSBuildThisFileDirectory)\CodeAnalysis\CodeAnalysis.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
      <PrivateAssets>All</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyDll" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy
      SourceFiles="$(OutDir)\$(AssemblyName).dll"
      DestinationFolder="$(AppData)\vbm\modules" />
  </Target>
</Project>