<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <RootNamespace>BossMod</RootNamespace>
  </PropertyGroup>

  <Import Project="..\Module.targets" />

  <ItemGroup>
    <EmbeddedResource Include="Dawntrail\DeepDungeon\PilgrimsTraverse\D99TheFinalVerse\Dark.json" />
    <EmbeddedResource Include="Dawntrail\DeepDungeon\PilgrimsTraverse\D99TheFinalVerse\Light.json" />
    <EmbeddedResource Include="Global\DeepDungeon\BadTraps.json" />
    <EmbeddedResource Include="Global\DeepDungeon\Walls.json" />
  </ItemGroup>
</Project>
